### ISSUE TITLE
CloudSuite incompatibility with Kubernetes

### ISSUE THREAD

**Issue by Remit** [parsa-epfl/cloudsuite#226]
Hello,

I was considering to use CloudSuite to benchmark some features that I've added to Kubernetes, but I've found out that Cloudsuite requires a substantial configuration in data-analytics benchmark to establish overlay networking between master and slave.

Prerequisites:
- single-node Kubernetes cluster with enough capacity, untainted node, and Calico as network plugin
- master-deployment.yaml (deploys and runs successfully):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsuite-data-analytics-master-deployment
  labels:
    app: cloudsuite-data-analytics-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsuite-data-analytics-master
  template:
    metadata:
      name: master
      labels:
        app: cloudsuite-data-analytics-master

    spec:
      hostname: master
      tolerations:
      - key: "allowed"
        operator: "Equal"
        # The value should be corrected for the real run. Also, one can use env variables.
        value: "k8instance"
        effect: "NoSchedule"
      containers:
      - name: master
        image: cloudsuite/data-analytics:latest
        # Reference for command arguments for entrypoint: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
        args: ["master"]
        ports:
          # Reference for Hadoop ports: https://ambari.apache.org/1.2.3/installing-hadoop-using-ambari/content/reference_chap2_1.html
          - name: http
            containerPort: 50070
          - name: https
            containerPort: 50470
          - name: ipc1
            containerPort: 8020
          - name: ipc2
            containerPort: 9000
        resources:
          requests:
            cpu: "0.5"
            memory: "4Gi"
          limits:
            cpu: "0.5"
            memory: "4Gi"
```

- worker-deployment.yaml (deploys and runs successfully):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsuite-data-analytics-worker-deployment
  labels:
    app: cloudsuite-data-analytics-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsuite-data-analytics-worker
  template:
    metadata:
      name: slave01
      labels:
        app: cloudsuite-data-analytics-worker
        numapolicy: numaaware
        # For baseline test only:
        testpolicy: antinuma

    spec:
      hostname: slave01
      tolerations:
      - key: "allowed"
        operator: "Equal"
        # The value should be corrected for the real run. Also, one can use env variables.
        value: "k8instance"
        effect: "NoSchedule"

      containers:
      - name: slave01
        image: cloudsuite/hadoop:latest
        # Reference for command arguments for entrypoint: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
        args: ["slave"]
        ports:
          # Reference for Hadoop ports: https://ambari.apache.org/1.2.3/installing-hadoop-using-ambari/content/reference_chap2_1.html
          - name: http
            containerPort: 50075
          - name: https
            containerPort: 50475
          - name: data
            containerPort: 50010
          - name: ipc
            containerPort: 50020
        resources:
          requests:
            cpu: "1.0"
            memory: "4Gi"
          limits:
            cpu: "1.0"
            memory: "4Gi"
```

Situation:
When running `benchmark` in master pod, the following error happens:

> 19/08/07 13:37:31 WARN hdfs.DFSClient: DataStreamer Exception
> org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /user/root/wiki._COPYING_ could only be replicated to 0 nodes instead of minReplication (=1).  There are 0 datanode(s) running and no node(s) are excluded in this operation.
>         at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1628)
>         at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getNewBlockTargets(FSNamesystem.java:3121)
>         at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3045)
>         at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:725)
>         at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:493)
>         at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
>         at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
>         at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
>         at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2217)
>         at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2213)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at javax.security.auth.Subject.doAs(Subject.java:422)
>         at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
>         at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2213)
> 
>         at org.apache.hadoop.ipc.Client.call(Client.java:1476)
>         at org.apache.hadoop.ipc.Client.call(Client.java:1413)
>         at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
>         at com.sun.proxy.$Proxy10.addBlock(Unknown Source)
>         at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:418)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
>         at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
>         at com.sun.proxy.$Proxy11.addBlock(Unknown Source)
>         at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1588)
>         at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1373)
>         at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:554)
> put: File /user/root/wiki._COPYING_ could only be replicated to 0 nodes instead of minReplication (=1).  There are 0 datanode(s) running and no node(s) are excluded in this operation.

When logging inside each container, I was able to see the other one by their IPs, e.g. 192.168.180.8 or 192.168.180.9. I also tried to change /etc/hosts and manually execute entrypoint.sh, but still no success in connection, e.g. slave tells:

> 2019-08-07 13:13:05,662 WARN org.apache.hadoop.hdfs.server.datanode.DataNode: Problem connecting to server: master:8020

So, to sum up: both master and slave work well independently (e.g. web-UI is in place) + they can see each other with ssh, but connection between them is not established. I think that there could be some networking issue, but I don't on which side it is: Kubernetes? settings of the Hadoop?

I have no experience with Hadoop, so I was wondering if you could help me figure out the solution.
Also, as a suggestion - maybe it would make sense to make Kubernetes deployments for the provided benchmarks? It would really expand the use of the Suite, I believe.

--
Best regards,
Vladimir
